### PR TITLE
fix: add license

### PR DESCRIPTION
**Pull request by maxbeatty**
requested by @akpala

### CODE REVIEW

**Review by zach-klippenstein — APPROVED** [review]
LGTM, but I'll let defer merging to @akpala.

**Review by zach-klippenstein — COMMENTED** [review]
Also, @maxbeatty i think you need to run the generator to update the HTML files too. 

```
./generate.pay
```

**Comment by maxbeatty** [comment]
I didn't intend to change anything about the published site, only add some licenses to the repo itself.

**Comment by zach-klippenstein** [comment]
Ah, for some reason I was thinking README.md was used in the generated site. My bad.

**Review by Retro64XYZ — APPROVED** [review]
This looks good. Glad to see the addition of a license here.

**Pull request merged**
